apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kbot
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  path: ./apps/kbot
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
