apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kbot
  namespace: default
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - kbot.example.com
  rules:
    - backendRefs:
        - name: kbot     # ІМ'Я СЕРВІСУ з чарту 
          port: 8080     # Порт HTTP сервісу бота 
