apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: kbot-src
        namespace: flux-system
      interval: 1m
      chart: ./helm/kbot
  values:
    image:
      registry: ghcr.io
      repository: kors-dev/kbot
      tag: "v2.2.2"   # тимчасово статичний; пізніше зробимо авто-бамп через CI
