apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: default
spec:
  interval: 1m
  timeout: 5m
  install:
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: kbot-oci
        namespace: flux-system
      chart: helm
      version: "2.2.3"     # <- публічний чарт у GHCR  
      interval: 1m
  values:
    image:
      repository: ghcr.io/kors-dev/kbot
      tag: "v2.2.3-938957b-linux-amd64"
